"""
Auto-labeling system for Brawl Stars dataset.
Uses heuristics and template matching to automatically label frames.
"""

import cv2
import numpy as np
from typing import List, Tuple, Dict, Optional
from pathlib import Path
from dataclasses import dataclass
import json


@dataclass
class AutoLabel:
    """A label generated by auto-labeling."""
    class_name: str
    bbox: Tuple[int, int, int, int]  # x1, y1, x2, y2
    confidence: float
    method: str  # "heuristic", "template", "color"


class HeuristicLabeler:
    """
    Labels objects using color and shape heuristics.
    """
    
    # Color ranges for different classes (HSV format)
    COLOR_RANGES = {
        "health_bar": {
            "green": (np.array([40, 50, 50]), np.array([80, 255, 255])),
            "red": (np.array([0, 50, 50]), np.array([10, 255, 255])),
        },
        "player": {
            "outline": (np.array([0, 0, 200]), np.array([180, 30, 255])),
        }
    }
    
    def __init__(self):
        pass
    
    def detect_health_bars(
        self,
        image: np.ndarray,
        min_width: int = 30,
        max_width: int = 150,
        min_height: int = 4,
        max_height: int = 12
    ) -> List[AutoLabel]:
        """
        Detect health bars using color segmentation.
        
        Args:
            image: BGR image
            
        Returns:
            List of health bar labels
        """
        labels = []
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        
        # Detect green health bars
        green_lower, green_upper = self.COLOR_RANGES["health_bar"]["green"]
        green_mask = cv2.inRange(hsv, green_lower, green_upper)
        
        # Detect red health bars (enemy)
        red_lower, red_upper = self.COLOR_RANGES["health_bar"]["red"]
        red_mask = cv2.inRange(hsv, red_lower, red_upper)
        
        # Find contours
        for mask, health_type in [(green_mask, "health_bar"), (red_mask, "health_bar")]:
            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            
            for cnt in contours:
                x, y, w, h = cv2.boundingRect(cnt)
                
                # Filter by size
                if min_width <= w <= max_width and min_height <= h <= max_height:
                    # Aspect ratio check (health bars are wide and thin)
                    if w / h > 3:
                        labels.append(AutoLabel(
                            class_name=health_type,
                            bbox=(x, y, x + w, y + h),
                            confidence=0.7,
                            method="color"
                        ))
        
        return labels
    
    def detect_players(
        self,
        image: np.ndarray,
        min_size: int = 40,
        max_size: int = 100
    ) -> List[AutoLabel]:
        """
        Detect players using circle detection and heuristics.
        
        Args:
            image: BGR image
            
        Returns:
            List of player labels
        """
        labels = []
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        # Detect circles (player bodies are roughly circular)
        circles = cv2.HoughCircles(
            gray,
            cv2.HOUGH_GRADIENT,
            dp=1,
            minDist=50,
            param1=50,
            param2=30,
            minRadius=min_size // 2,
            maxRadius=max_size // 2
        )
        
        if circles is not None:
            circles = np.uint16(np.around(circles))
            
            for circle in circles[0, :]:
                x, y, r = circle
                
                # Convert circle to bbox
                x1 = int(x - r)
                y1 = int(y - r)
                x2 = int(x + r)
                y2 = int(y + r)
                
                labels.append(AutoLabel(
                    class_name="player",
                    bbox=(x1, y1, x2, y2),
                    confidence=0.6,
                    method="heuristic"
                ))
        
        return labels
    
    def detect_walls(
        self,
        image: np.ndarray
    ) -> List[AutoLabel]:
        """
        Detect walls using edge detection and color analysis.
        
        Args:
            image: BGR image
            
        Returns:
            List of wall labels
        """
        labels = []
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        
        # Walls are typically brown/gray with low saturation
        # This is a simplified heuristic
        lower_wall = np.array([0, 0, 50])
        upper_wall = np.array([30, 80, 150])
        
        wall_mask = cv2.inRange(hsv, lower_wall, upper_wall)
        
        # Morphological operations to connect wall segments
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (20, 20))
        wall_mask = cv2.morphologyEx(wall_mask, cv2.MORPH_CLOSE, kernel)
        
        # Find large contours
        contours, _ = cv2.findContours(wall_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        for cnt in contours:
            x, y, w, h = cv2.boundingRect(cnt)
            
            # Filter large objects (walls are big)
            if w > 50 and h > 50:
                labels.append(AutoLabel(
                    class_name="wall",
                    bbox=(x, y, x + w, y + h),
                    confidence=0.5,
                    method="heuristic"
                ))
        
        return labels
    
    def detect_bushes(
        self,
        image: np.ndarray
    ) -> List[AutoLabel]:
        """
        Detect bushes using green color detection.
        
        Args:
            image: BGR image
            
        Returns:
            List of bush labels
        """
        labels = []
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        
        # Bushes are green
        lower_green = np.array([35, 40, 40])
        upper_green = np.array([85, 255, 255])
        
        bush_mask = cv2.inRange(hsv, lower_green, upper_green)
        
        # Morphological operations
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
        bush_mask = cv2.morphologyEx(bush_mask, cv2.MORPH_CLOSE, kernel)
        
        contours, _ = cv2.findContours(bush_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        for cnt in contours:
            x, y, w, h = cv2.boundingRect(cnt)
            
            # Filter by size
            if w > 40 and h > 40:
                labels.append(AutoLabel(
                    class_name="bush",
                    bbox=(x, y, x + w, y + h),
                    confidence=0.6,
                    method="color"
                ))
        
        return labels


class TemplateMatcher:
    """
    Template matching for specific Brawl Stars elements.
    """
    
    def __init__(self, templates_dir: Optional[Path] = None):
        self.templates: Dict[str, np.ndarray] = {}
        self.templates_dir = templates_dir
        
        if templates_dir and templates_dir.exists():
            self._load_templates()
    
    def _load_templates(self):
        """Load template images from directory."""
        template_files = [
            ("ammo_icon", "ammo.png"),
            ("super_icon", "super.png"),
            ("player_indicator", "player_indicator.png"),
            ("enemy_indicator", "enemy_indicator.png"),
        ]
        
        for name, filename in template_files:
            template_path = self.templates_dir / filename
            if template_path.exists():
                template = cv2.imread(str(template_path), cv2.IMREAD_GRAYSCALE)
                if template is not None:
                    self.templates[name] = template
    
    def match_template(
        self,
        image: np.ndarray,
        template_name: str,
        threshold: float = 0.7
    ) -> List[AutoLabel]:
        """
        Match a template in the image.
        
        Args:
            image: BGR or grayscale image
            template_name: Name of loaded template
            threshold: Match confidence threshold
            
        Returns:
            List of matching locations
        """
        labels = []
        
        if template_name not in self.templates:
            return labels
        
        template = self.templates[template_name]
        
        if len(image.shape) == 3:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        else:
            gray = image
        
        # Template matching
        result = cv2.matchTemplate(gray, template, cv2.TM_CCOEFF_NORMED)
        
        # Find matches above threshold
        locations = np.where(result >= threshold)
        
        h, w = template.shape
        
        for pt in zip(*locations[::-1]):
            x, y = pt
            confidence = result[y, x]
            
            labels.append(AutoLabel(
                class_name=template_name,
                bbox=(x, y, x + w, y + h),
                confidence=float(confidence),
                method="template"
            ))
        
        return labels


class AutoLabeler:
    """
    Main auto-labeling orchestrator.
    Combines heuristics and template matching.
    """
    
    def __init__(self, templates_dir: Optional[Path] = None):
        self.heuristic = HeuristicLabeler()
        self.template = TemplateMatcher(templates_dir)
        
        # Confidence thresholds for accepting labels
        self.min_confidence = {
            "player": 0.6,
            "enemy": 0.6,
            "wall": 0.5,
            "bush": 0.5,
            "health_bar": 0.7,
            "ammo": 0.8,
            "super": 0.8,
        }
    
    def label_image(
        self,
        image_path: Path,
        output_format: str = "yolo"
    ) -> List[AutoLabel]:
        """
        Auto-label a single image.
        
        Args:
            image_path: Path to image file
            output_format: "yolo" or "coco"
            
        Returns:
            List of generated labels
        """
        image = cv2.imread(str(image_path))
        if image is None:
            return []
        
        all_labels = []
        
        # Run all detection methods
        all_labels.extend(self.heuristic.detect_health_bars(image))
        all_labels.extend(self.heuristic.detect_players(image))
        all_labels.extend(self.heuristic.detect_walls(image))
        all_labels.extend(self.heuristic.detect_bushes(image))
        
        # Template matching
        for template_name in self.template.templates.keys():
            all_labels.extend(self.template.match_template(image, template_name))
        
        # Filter by confidence
        filtered_labels = []
        for label in all_labels:
            min_conf = self.min_confidence.get(label.class_name, 0.5)
            if label.confidence >= min_conf:
                filtered_labels.append(label)
        
        # Non-maximum suppression for overlapping boxes
        filtered_labels = self._nms(filtered_labels, iou_threshold=0.5)
        
        return filtered_labels
    
    def label_dataset(
        self,
        images_dir: Path,
        output_dir: Path,
        output_format: str = "yolo"
    ) -> Dict:
        """
        Auto-label entire dataset.
        
        Args:
            images_dir: Directory containing images
            output_dir: Directory to save labels
            output_format: "yolo" or "coco"
            
        Returns:
            Statistics dict
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        
        stats = {
            "total_images": 0,
            "labeled_images": 0,
            "total_labels": 0,
            "labels_by_class": {}
        }
        
        image_extensions = {".jpg", ".jpeg", ".png", ".bmp"}
        
        for image_path in images_dir.iterdir():
            if image_path.suffix.lower() not in image_extensions:
                continue
            
            stats["total_images"] += 1
            
            labels = self.label_image(image_path, output_format)
            
            if labels:
                stats["labeled_images"] += 1
                stats["total_labels"] += len(labels)
                
                for label in labels:
                    class_name = label.class_name
                    stats["labels_by_class"][class_name] = stats["labels_by_class"].get(class_name, 0) + 1
                
                # Save labels
                if output_format == "yolo":
                    self._save_yolo_labels(image_path, labels, output_dir)
                elif output_format == "coco":
                    self._save_coco_labels(image_path, labels, output_dir)
        
        return stats
    
    def _nms(
        self,
        labels: List[AutoLabel],
        iou_threshold: float = 0.5
    ) -> List[AutoLabel]:
        """Non-maximum suppression for overlapping boxes."""
        if not labels:
            return []
        
        # Sort by confidence
        sorted_labels = sorted(labels, key=lambda l: -l.confidence)
        
        keep = []
        
        while sorted_labels:
            current = sorted_labels[0]
            keep.append(current)
            
            # Remove overlapping boxes
            sorted_labels = [
                l for l in sorted_labels[1:]
                if not self._iou_overlap(current.bbox, l.bbox, iou_threshold)
            ]
        
        return keep
    
    def _iou_overlap(
        self,
        box1: Tuple[int, int, int, int],
        box2: Tuple[int, int, int, int],
        threshold: float
    ) -> bool:
        """Check if two boxes overlap above threshold."""
        x1_1, y1_1, x2_1, y2_1 = box1
        x1_2, y1_2, x2_2, y2_2 = box2
        
        xi1 = max(x1_1, x1_2)
        yi1 = max(y1_1, y1_2)
        xi2 = min(x2_1, x2_2)
        yi2 = min(y2_1, y2_2)
        
        inter_width = max(0, xi2 - xi1)
        inter_height = max(0, yi2 - yi1)
        inter_area = inter_width * inter_height
        
        box1_area = (x2_1 - x1_1) * (y2_1 - y1_1)
        box2_area = (x2_2 - x1_2) * (y2_2 - y1_2)
        
        if box1_area == 0 or box2_area == 0:
            return False
        
        iou = inter_area / min(box1_area, box2_area)
        
        return iou > threshold
    
    def _save_yolo_labels(
        self,
        image_path: Path,
        labels: List[AutoLabel],
        output_dir: Path
    ):
        """Save labels in YOLO format."""
        # Read image to get dimensions
        image = cv2.imread(str(image_path))
        if image is None:
            return
        
        height, width = image.shape[:2]
        
        # Class mapping
        class_map = {
            "player": 0,
            "enemy": 1,
            "wall": 2,
            "bush": 3,
            "health_bar": 4,
            "ammo": 5,
            "super": 6,
        }
        
        # Build YOLO format lines
        lines = []
        for label in labels:
            class_id = class_map.get(label.class_name, 0)
            
            x1, y1, x2, y2 = label.bbox
            
            # Convert to YOLO format (normalized center x, y, width, height)
            box_width = x2 - x1
            box_height = y2 - y1
            center_x = (x1 + x2) / 2 / width
            center_y = (y1 + y2) / 2 / height
            norm_width = box_width / width
            norm_height = box_height / height
            
            lines.append(
                f"{class_id} {center_x:.6f} {center_y:.6f} {norm_width:.6f} {norm_height:.6f}"
            )
        
        # Save to file
        label_path = output_dir / f"{image_path.stem}.txt"
        with open(label_path, 'w') as f:
            f.write('\n'.join(lines))
    
    def _save_coco_labels(
        self,
        image_path: Path,
        labels: List[AutoLabel],
        output_dir: Path
    ):
        """Save labels in COCO format (placeholder)."""
        # COCO format requires accumulating all annotations
        # This is a simplified version
        pass


def auto_label_dataset(
    images_dir: str,
    output_dir: str,
    templates_dir: Optional[str] = None,
    format: str = "yolo"
) -> Dict:
    """
    Convenience function to auto-label a dataset.
    
    Args:
        images_dir: Directory with images
        output_dir: Directory for output labels
        templates_dir: Optional directory with templates
        format: Output format ("yolo" or "coco")
        
    Returns:
        Statistics dict
    """
    labeler = AutoLabeler(
        templates_dir=Path(templates_dir) if templates_dir else None
    )
    
    return labeler.label_dataset(
        Path(images_dir),
        Path(output_dir),
        format
    )
